# Laravel Cloud Configuration
name: vpn-app

# Build configuration
build:
  commands:
    - npm ci
    - npm run build
    - composer install --no-dev --optimize-autoloader
    - php artisan config:cache

# Environment variables
environments:
  production:
    variables:
      APP_ENV: production
      APP_DEBUG: false
      LOG_CHANNEL: stderr
      SESSION_DRIVER: database
      CACHE_DRIVER: database
      DB_CONNECTION: mysql
      DB_HOST: database.internal
      DB_PORT: 3306
      DB_DATABASE: main
      DB_USERNAME: main
      DB_PASSWORD: ""

# Web configuration
web:
  document_root: /public
  passthru: /index.php
  rules:
    - if: "{path} matches '/build/.*'"
      expires: 1y
      headers:
        Cache-Control: "public, immutable"

# Services
services:
  database:
    type: mysql:8.0
    disk: 1024

# Relationships
relationships:
  database: "database:mysql"

# Storage
storage:
  - name: uploads
    mount: /storage/app/public
    source:
      service: files
      source_path: uploads